import { StorageProbeSchedule } from './storage-probe.schedule'

describe('storage probe start-anchored schedule', () => {
  beforeEach(() => {
    jest.useFakeTimers()
    jest.setSystemTime(0)
  })
  afterEach(() => jest.useRealTimers())
  it('shortens/extends from actual start and does not postpone unchanged values', async () => {
    const launch = jest.fn()
    const s = new StorageProbeSchedule(600, launch)
    s.enable()
    s.started()
    s.settled()
    await jest.advanceTimersByTimeAsync(10_000)
    s.apply(60)
    expect(s.nextScheduledAt).toBe(new Date(60_000).toISOString())
    s.apply(600)
    expect(s.nextScheduledAt).toBe(new Date(600_000).toISOString())
    s.apply(600)
    await jest.advanceTimersByTimeAsync(590_000)
    expect(launch).toHaveBeenCalledTimes(1)
    s.stop()
  })
  it('keeps an active slot without a timer, uses latest value on settlement and runs overdue once', async () => {
    const launch = jest.fn()
    const s = new StorageProbeSchedule(600, launch)
    s.enable()
    s.started()
    await jest.advanceTimersByTimeAsync(90_000)
    s.apply(120)
    s.apply(60)
    expect(s.nextScheduledAt).toBeNull()
    expect(launch).not.toHaveBeenCalled()
    s.settled()
    expect(s.nextScheduledAt).toBe(new Date(90_000).toISOString())
    await jest.advanceTimersByTimeAsync(1)
    expect(launch).toHaveBeenCalledTimes(1)
    s.started()
    s.settled()
    s.stop()
    await jest.advanceTimersByTimeAsync(600_000)
    expect(launch).toHaveBeenCalledTimes(1)
  })
})
