export const AUDIT_ACTIONS = [
  'admin.cleanup.executed',
  'admin.user.sessions_revoked',
  'admin.user.system_role_changed',
  'ai.approval.approved',
  'ai.approval.expired',
  'ai.approval.rejected',
  'ai.approval.requested',
  'ai.assistant.created',
  'ai.assistant.disabled',
  'ai.assistant.enabled',
  'ai.assistant.updated',
  'ai.assistant.version_published',
  'ai.conversation.operator_message',
  'ai.conversation.released',
  'ai.conversation.taken_over',
  'ai.conversation.transcript_accessed',
  'ai.tool.execution_failed',
  'ai.tool.invoked',
  'api_key.created',
  'api_key.revoked',
  'auth.step_up_failed',
  'auth.step_up_succeeded',
  'org.invite_accepted',
  'org.invite_created',
  'org.invite_revoked',
  'telegram.connection_linked',
  'telegram.connection_unlinked',
] as const

export type AuditAction = (typeof AUDIT_ACTIONS)[number]
